backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: "doc" # Used in routes, e.g., /admin/collections/blog
  label: "Doc" # Used in the UI
  folder: "docs" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}{{name}}" # Filename template, e.g., title.md
  identifier_field: "route"
  extension: "mdx"
  format: "frontmatter"
  fields: # The fields for each document, usually in front matter
  - label: "Name"
    name: "name"
  - label: "Menu"
    name: "menu"
    required: false
  - label: "Route"
    name: "route"
  - label: "Body"
    name: "body"
    widget: "markdown"